eventex/core/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('eventex.core.views',
    url(r'^$', 'home', name='home'),
    url(r'^palestrantes/(?P<slug>[\w-]+)/$', 'speaker_detail', name='speaker_detail'),
    url(r'^palestras/$', 'talk_list', name='talk_list'),
    url(r'^palestras/(?P<id>\d+)/$', 'talk_detail', name='talk_detail'),
)

eventex/subscriptions/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('eventex.subscriptions.views',
    url(r'^(\d+)/$', 'detail', name='detail'),
    url(r'^$', 'subscribe', name='subscribe'),
)

eventex/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^inscricao/', include('eventex.subscriptions.urls', namespace='subscriptions')),
    url(r'', include('eventex.core.urls', namespace='core')),
)

eventex/core/models.py
# coding: utf-8
from django.db import models
from django.utils.translation import ugettext_lazy as _
from eventex.core.managers import KindContactManager, PeriodManager
from django.core.urlresolvers import reverse as r

class Speaker(models.Model):
    name = models.CharField(_(u'Nome'), max_length=255)
    description = models.TextField(_(u'Descrição'))
    url = models.URLField(_(u'URL'))
    slug = models.SlugField(_(u'Slug'))

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('core:speaker_detail', (), {'slug': self.slug})

    class Meta:
        verbose_name = 'palestrante'
        verbose_name_plural = 'palestrantes'


class Contact(models.Model):
    KINDS = (
        ('E', 'E-mail'),
        ('P', 'Telefone'),
        ('F', 'Fax'),
    )

    speaker = models.ForeignKey('Speaker')
    kind = models.CharField(_(u'Tipo'), max_length=1, choices=KINDS)
    value = models.CharField(_(u'Valor'), max_length=255)

    objects = models.Manager()
    emails = KindContactManager(kind='E')
    phones = KindContactManager(kind='P')
    faxes = KindContactManager(kind='F')

    def __unicode__(self):
        return self.value

    class Meta:
        verbose_name = 'contato'
        verbose_name_plural = 'contatos'


class Talk(models.Model):
    title = models.CharField(_(u'Título'), max_length=200)
    description = models.TextField(_(u'Descrição da palestra'))
    start_time = models.TimeField(_(u'Horário'), blank=True)
    speakers = models.ManyToManyField('Speaker', verbose_name=_(u'palestrantes'))

    objects = PeriodManager()

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return '/palestras/%d/' % self.pk
        #return r('core:talk_detail', self.pk)

    class Meta:
        verbose_name = 'palestra'
        verbose_name_plural = 'palestras'

eventex/subscriptions/models.py
# coding: utf-8
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Subscription(models.Model):
    name = models.CharField(_('Nome'), max_length=100)
    cpf = models.CharField(_('CPF'), max_length=11, unique=True)
    email = models.EmailField(_('E-mail'), blank=True)
    phone = models.CharField(_('Telefone'), max_length=20, blank=True)
    created_at = models.DateTimeField(_(u'Criado em'), auto_now_add=True)
    paid = models.BooleanField(_(u'Pago'), default=False)

    class Meta:
        ordering = ['created_at']
        verbose_name = _(u'incrição')
        verbose_name_plural = _(u'incrições')
        #app_label = _(u'Inscrições')

    def __unicode__(self):
        return self.name

eventex/subscriptions/forms.py
# coding: utf-8
from django import forms
from django.utils.translation import ugettext as _
from django.core.exceptions import ValidationError
from django.core.validators import EMPTY_VALUES
from eventex.subscriptions.models import Subscription

def CPFValidator(value):
    if not value.isdigit():
        raise ValidationError(_(u'CPF deve conter apenas números'))

    if len(value) != 11:
        raise ValidationError(_(u'CPF deve ter 11 números'))


class PhoneWidget(forms.MultiWidget):
    def __init__(self, attrs=None):
        widgets = (
            forms.TextInput(attrs=attrs),
            forms.TextInput(attrs=attrs),
            )
        super(PhoneWidget, self).__init__(widgets, attrs)

    def decompress(self, value):
        if not value:
            return [None, None]
        return value.split('-')


class PhoneField(forms.MultiValueField):
    widget = PhoneWidget

    def __init__(self, *args, **kwargs):
        fields = (
            forms.IntegerField(),
            forms.IntegerField(),
            )
        super(PhoneField, self).__init__(fields, *args, **kwargs)

    def compress(self, data_list):
        if not data_list:
            return ''
        if data_list[0] in EMPTY_VALUES:
            raise forms.ValidationError(_(u'DDD inválido'))
        if data_list[1] in EMPTY_VALUES:
            raise forms.ValidationError(_(u'Número inválido'))
        return '%s-%s' % tuple(data_list)


class SubscriptionForm(forms.ModelForm):
    phone = PhoneField(label=_('Telefone'), required=False)

    class Meta:
        model = Subscription
        exclude = ('paid',)

    def __init__(self, *args, **kwargs):
        super(SubscriptionForm, self).__init__(*args, **kwargs)

        self.fields['cpf'].validators.append(CPFValidator)

    def clean(self):
        super(SubscriptionForm, self).clean()

        if not self.cleaned_data.get('email') \
           and not self.cleaned_data.get('phone'):
            raise ValidationError(_(u'Informe seu e-mail ou telefone'))

        return self.cleaned_data

    def clean_name(self):
        def capitalize(word):
            word = word.capitalize()
            if word in ['De', 'Da', 'Dos', 'Das']:
                word = word.lower()
            return word

        name = self.cleaned_data['name']
        words = map(lambda w: capitalize(w), name.split())
        capitalized_name = ' '.join(words)
        return capitalized_name
        

eventex/core/views.py
from django.shortcuts import render, get_object_or_404
from eventex.core.models import Speaker, Talk

def home(request):
    return render(request, 'index.html')


def speaker_detail(request, slug):
    speaker = get_object_or_404(Speaker, slug=slug)
    context = {'speaker': speaker}
    return render(request, 'core/speaker_detail.html', context)


def talk_list(request):
    context = {
        'morning_talks': Talk.objects.at_morning(),
        'afternoon_talks': Talk.objects.at_afternoon()
    }
    return render(request, 'core/talk_list.html', context)

def talk_detail(request, id):
    return render(request, 'core/talk_detail.html')

eventex/subscriptions/views.py
# coding: utf-8
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from eventex.subscriptions.forms import SubscriptionForm
from eventex.subscriptions.models import Subscription
from django.core.urlresolvers import reverse as r

def subscribe(request):
    if request.method == 'POST':
        return create(request)
    else:
        return new(request)

def create(request):
    form = SubscriptionForm(request.POST)
    if form.is_valid():
        obj = form.save()
        return HttpResponseRedirect(r('subscriptions:detail', args=[obj.pk]))
    else:
        return render(request, 'subscriptions/subscriptions_form.html',
            {'form': form})

def new(request):
    return render(request, 'subscriptions/subscriptions_form.html',
        {'form': SubscriptionForm()})

def detail(request, pk):
    s = get_object_or_404(Subscription, pk=pk)
    return render(request, 'subscriptions/subscriptions_detail.html', 
        {'subscription': s})

eventex/core/templates/base.html
<!doctype html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="description" content="EventeX" />
  <meta http-equiv='content-Language' content='pt-BR' />
  <link type="image/x-icon" href="{{ STATIC_URL }}favicon.ico" rel="shortcut icon" />
 
  <title>EventeX</title>
 
  <link type="text/css" href="{{ STATIC_URL }}css/style.css" rel="stylesheet" media="screen" />
 
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.0/jquery.min.js"></script>
</head>
<body>

  <div id="page">
    <div id="header">
      <center>
        <a href="/"><img src="{{ STATIC_URL }}img/logo.png" alt="EventeX" /></a>
      </center>
    </div>
    <hr>
    <div id="content">
      {% block content %}
      {% endblock content %}
    </div>
    <hr>
    <div id="footer">
      <p>&copy; 2012. <a rel="license" href="{% url 'core:home' %}">EventeX</a>, some rights reserved. <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/br/80x15.png" /></a><a href="http://www.djangoproject.com/" id="django"><img src="https://djangoproject.com/s/img/badges/djangosite100x25.gif" border="0" alt="A Django site." title="A Django site." /></a></p>
    </div>
  </div>
</body>
</html>

eventex/core/templates/core/speaker_detail.html
{% extends 'base.html' %}

{% block content %}
        <h4><a href="{{ speaker.url }}">{{ speaker.name }}</a></h4>
        <p>{{ speaker.description }}</p>
{% endblock content %}

eventex/core/templates/core/talk_list.html
{% extends 'base.html' %}

{% block content %}
        <h3>Manhã</h3>
        {% for talk in morning_talks %}
            {% include 'core/talk_list_snippet.html' %}
        {% empty %}
            <p>Não existem palestras durante a manhã</p>
        {% endfor %}
        <h3>Tarde</h3>
        {% for talk in afternoon_talks %}
            {% include 'core/talk_list_snippet.html' %}
        {% empty %}
            <p>Não existem palestras durante a tarde</p>
        {% endfor %}
{% endblock content %}

eventex/core/templates/core/talk_list_snippet.html
<div class="palestra">
    <h4>
        <a href="{{ talk.get_absolute_url }}">
            {{ talk.start_time}} - {{talk.title}}
        </a>
    </h4>
    {% for speaker in talk.speakers.all %}
        <h5>
            <a href="{{ speaker.get_absolute_url }}"
               title="{{ speaker.description|truncatewords:30 }}">
            {{ speaker.name }}
            </a>
        </h5>
    {% endfor %}
    <p>{{ talk.description }}</p>
</div>

eventex/core/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Bem-vindo ao EventeX!</h1>
    <p>O evento mais sensacional do ano depois do Dev in Rio!</p>
    <p>Você não pode perder esta oportunidade!</p>
    <p><strong><a href="{% url 'subscriptions:subscribe' %}">Inscreva-se já!</a></strong></p>
    <p>Para dúvidas e mais informações entre em contato com <a href="mailto:eventex@eventex.com.br">eventex@eventex.com.br</a></p>
{% endblock content %}

eventex/subscriptions/templates/subscriptions/subscriptions_detail.html
{% extends 'base.html' %}

{% block content %}
    <p>Parabéns, {{ subscription.name }}</p>
    <p>Sua inscrição foi realizada com sucesso em 
        {{ subscription.created_at|date:"d/m/Y" }}
        às {{ subscription.created_at|date:"H:i" }}.
    </p>
    <p>Em breve entraremos em contato pelo
    {% if subscription.phone %}
        telefone {{ subscription.phone }}.
    {% else %}
        e-mail {{ subscription.email }}.
    {% endif %}
    </p>
{% endblock content %}

eventex/subscriptions/templates/subscriptions/subscriptions_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>Formulário de inscrição</h1>
    <form action="." method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <p>
            <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
            {{ form.name }}
            {{ form.name.errors }}
        </p>
        <p>
            <label for="{{ form.cpf.id_for_label }}">{{ form.cpf.label }}</label>
            {{ form.cpf }}
            {{ form.cpf.errors }}
        </p>
        <p>
            <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
            {{ form.email }}
            {{ form.email.errors }}
        </p>
        <p>
            <label for="{{ form.phone.id_for_label }}">{{ form.phone.label }}</label>
            {{ form.phone }}
            {{ form.phone.errors }}
        </p>
        <input type="submit" value="Enviar!" class="button" />
    </form>
{% endblock content %}